POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
  "_id": "5a422a851b54a676234d17f4",
  "title": "Testing Single Blog insert",
  "author": "An Author",
  "url": "https://reactpatterns.com/",
  "likes": 17,
  "__v": 0
  # "userId": "5e823ca288236d3048a46c19"
}